version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-backend
    ports:
      - "6380:6380"
    volumes:
      - redis-data:/data
    
    networks:            
      - backendnetwork   
  frontend:
    image: frontend-image
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - backendnetwork
    environment:
      - BACKEND_DNS=backend

  backend:
    image: backend-image
    ports:
      - "9000:9000"
    networks:
      - backendnetwork
    environment:
      - REDIS_DNS=redis-backend
    depends_on:
      - redis
    
networks:
  backendnetwork:
volumes:
  redis-data: 