version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-backend
    ports:
      - "6380:6380"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - backendnetwork
    environment:
      - BACKEND_DNS=backend

  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    networks:
      - backendnetwork
    environment:
      - REDIS_DNS=redis-backend
networks:
  backendnetwork:
volumes:
  redis-data: 