name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env: 
  docker_username: harun8
  docker_password: mohammedharunabdi
  GIT_COMMIT: ${{ github.sha }}

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f frontend/kubernetes/frontend-deployment.yaml
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f backend/kubernetes/backend-deployment.yaml

        
  build-and-test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build frontend
        working-directory: frontend
        run: go build

      - name: Run tests
        working-directory: frontend
        run: go test ./...


  Docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test-frontend
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "$docker_password" | docker login -u "$docker_username" --password-stdin

      - name: Build Docker image
        run: docker build -t $docker_username/myapp:$GIT_COMMIT ./backend

      - name: Push Docker image to DockerHub
        run: docker push $docker_username/myapp:$GIT_COMMIT


