name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env: 
  docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
  docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build frontend
        working-directory: frontend
        run: go build

      - name: Run tests
        working-directory: frontend
        run: go test ./...

  Docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test-frontend # reference the correct job name
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # This will get the code to this job

      - name: Login to DockerHub
        run: echo "$docker_password" | docker login -u "$docker_username" --password-stdin

      - name: Build Docker image
        run: docker build -t $docker_username/myapp:$GIT_COMMIT .

      - name: Push Docker image to DockerHub
        run: docker push $docker_username/myapp:$GIT_COMMIT
