name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env: 
  docker_username: harun8
  docker_password: mohammedharunabdi
  GIT_COMMIT: ${{ github.sha }}

jobs:

  build-and-test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build frontend
        working-directory: frontend
        run: go build

      - name: Run tests
        working-directory: frontend
        run: go test ./...

  Docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test-frontend
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:$GIT_COMMIT ./backend

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:$GIT_COMMIT

  deploy:
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy frontend Kubernetes
        run: kubectl apply -f frontend/kubernetes/frontend-deployment.yaml
        
      - name: Deploy backend Kubernetes
        run: kubectl apply -f backend/kubernetes/backend-deployment.yaml
